// FIFA Ultimate XI — first two names only, all 99 rated, ES6 image imports
import vanDerSarImg from "../assets/players/van_der_sar.jpg";
import robertoCarlosImg from "../assets/players/roberto_carlos.jpg";
import cannavaroImg from "../assets/players/cannavaro.jpg";
import maldiniImg from "../assets/players/maldini.jpg";
import marceloImg from "../assets/players/marcelo.jpg";
import keaneImg from "../assets/players/roy_keane.jpg";
import kakaImg from "../assets/players/kaka.jpg";
import ozilImg from "../assets/players/ozil.webp";
import cr7Img from "../assets/players/cr7.jpg";
import messiImg from "../assets/players/messi.jpg";
import neymarImg from "../assets/players/neymar.jpg";

const players = [
  {
    name: "Van Der Sar",
    team: "Man United",
    nationality: "Netherlands",
    position: "GK",
    jerseyNumber: 1,
    age: 40,
    rating: 99,
    image: vanDerSarImg,
    captain: false,
    x: 50, y: 88,
  },
  {
    name: "Roberto Carlos",
    team: "Brazil",
    nationality: "Brazil",
    position: "RB",
    jerseyNumber: 6,
    age: 25,
    rating: 99,
    image: robertoCarlosImg,
    captain: false,
    x: 82, y: 70,
  },
  {
    name: "Fabio Cannavaro",
    team: "Italy",
    nationality: "Italy",
    position: "CB",
    jerseyNumber: 5,
    age: 33,
    rating: 99,
    image: cannavaroImg,
    captain: false,
    x: 60, y: 73,
  },
  {
    name: "Paolo Maldini",
    team: "AC Milan",
    nationality: "Italy",
    position: "CB",
    jerseyNumber: 3,
    age: 35,
    rating: 99,
    image: maldiniImg,
    captain: true,
    x: 40, y: 73,
  },
  {
    name: "Marcelo",
    team: "Real Madrid",
    nationality: "Brazil",
    position: "LB",
    jerseyNumber: 12,
    age: 30,
    rating: 99,
    image: marceloImg,
    captain: false,
    x: 18, y: 70,
  },
  {
    name: "Roy Keane",
    team: "Man United",
    nationality: "Ireland",
    position: "CDM",
    jerseyNumber: 16,
    age: 32,
    rating: 99,
    image: keaneImg,
    captain: false,
    x: 50, y: 53,
  },
  {
    name: "Ricardo Kaká",
    team: "AC Milan",
    nationality: "Brazil",
    position: "CAM",
    jerseyNumber: 22,
    age: 25,
    rating: 99,
    image: kakaImg,
    captain: false,
    x: 72, y: 45,
  },
  {
    name: "Mesut Özil",
    team: "Arsenal",
    nationality: "Germany",
    position: "CAM",
    jerseyNumber: 10,
    age: 27,
    rating: 99,
    image: ozilImg,
    captain: false,
    x: 28, y: 45,
  },
  {
    name: "Cristiano Ronaldo",
    team: "Man United",
    nationality: "Portugal",
    position: "ST",
    jerseyNumber: 7,
    age: 23,
    rating: 99,
    image: cr7Img,
    captain: false,
    x: 50, y: 12,
  },
  {
    name: "Lionel Messi",
    team: "Barcelona",
    nationality: "Argentina",
    position: "RW",
    jerseyNumber: 10,
    age: 24,
    rating: 99,
    image: messiImg,
    captain: false,
    x: 78, y: 22,
  },
  {
    name: "Neymar",
    team: "Santos",
    nationality: "Brazil",
    position: "LW",
    jerseyNumber: 11,
    age: 21,
    rating: 99,
    image: neymarImg,
    captain: false,
    x: 22, y: 22,
  },
];

export default players;
