// Player data — confirmed details (full names, nationalities, jersey numbers, ages at peak/career era)
const players = [
  {
    name: "Edwin van der Sar",
    team: "Manchester United",
    nationality: "Netherlands",
    position: "GK",
    jerseyNumber: 1,
    age: 40,
    image: "/players/van_der_sar.jpg",
  },
  {
    name: "Roberto Carlos da Silva Rocha",
    team: "Brazil National Team",
    nationality: "Brazil",
    position: "RB",
    jerseyNumber: 6,
    age: 25,
    image: "/players/roberto_carlos.jpg",
  },
  {
    name: "Fabio Cannavaro",
    team: "Italy National Team",
    nationality: "Italy",
    position: "CB",
    jerseyNumber: 5,
    age: 33,
    image: "/players/cannavaro.jpg",
  },
  {
    name: "Paolo Maldini",
    team: "AC Milan",
    nationality: "Italy",
    position: "CB",
    jerseyNumber: 3,
    age: 35,
    image: "/players/maldini.jpg",
  },
  {
    name: "Marcelo Vieira da Silva Júnior",
    team: "Real Madrid",
    nationality: "Brazil",
    position: "LB",
    jerseyNumber: 12,
    age: 30,
    image: "/players/marcelo.jpg",
  },
  {
    name: "Roy Maurice Keane",
    team: "Manchester United",
    nationality: "Republic of Ireland",
    position: "CDM",
    jerseyNumber: 16,
    age: 32,
    image: "/players/roy_keane.jpg",
  },
  {
    name: "Ricardo Izecson dos Santos Leite (Kaká)",
    team: "AC Milan",
    nationality: "Brazil",
    position: "CAM",
    jerseyNumber: 22,
    age: 25,
    image: "/players/kaka.jpg",
  },
  {
    name: "Mesut Özil",
    team: "Arsenal FC",
    nationality: "Germany",
    position: "CAM",
    jerseyNumber: 10,
    age: 27,
    image: "/players/ozil.webp",
  },
  {
    name: "Cristiano Ronaldo dos Santos Aveiro",
    team: "Manchester United",
    nationality: "Portugal",
    position: "RW",
    jerseyNumber: 7,
    age: 23,
    image: "/players/cr7.jpg",
  },
  {
    name: "Lionel Andrés Messi Cuccittini",
    team: "FC Barcelona",
    nationality: "Argentina",
    position: "LW",
    jerseyNumber: 10,
    age: 24,
    image: "/players/messi.jpg",
  },
  {
    name: "Dimitar Ivanov Berbatov",
    team: "Manchester United",
    nationality: "Bulgaria",
    position: "ST",
    jerseyNumber: 9,
    age: 29,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Dimitar_Berbatov_2012.jpg/640px-Dimitar_Berbatov_2012.jpg",
  },
];

export default players;
