// FIFA Ultimate XI — first two names only, all 99 rated
const players = [
  {
    name: "Edwin van der Sar",
    team: "Manchester United",
    nationality: "Netherlands",
    position: "GK",
    jerseyNumber: 1,
    age: 40,
    rating: 99,
    image: "/players/van_der_sar.jpg",
    captain: false,
    x: 50, y: 90, // pitch position %
  },
  {
    name: "Roberto Carlos",
    team: "Brazil",
    nationality: "Brazil",
    position: "RB",
    jerseyNumber: 6,
    age: 25,
    rating: 99,
    image: "/players/roberto_carlos.jpg",
    captain: false,
    x: 85, y: 72,
  },
  {
    name: "Fabio Cannavaro",
    team: "Italy",
    nationality: "Italy",
    position: "CB",
    jerseyNumber: 5,
    age: 33,
    rating: 99,
    image: "/players/cannavaro.jpg",
    captain: false,
    x: 62, y: 75,
  },
  {
    name: "Paolo Maldini",
    team: "AC Milan",
    nationality: "Italy",
    position: "CB",
    jerseyNumber: 3,
    age: 35,
    rating: 99,
    image: "/players/maldini.jpg",
    captain: true,
    x: 38, y: 75,
  },
  {
    name: "Marcelo Vieira",
    team: "Real Madrid",
    nationality: "Brazil",
    position: "LB",
    jerseyNumber: 12,
    age: 30,
    rating: 99,
    image: "/players/marcelo.jpg",
    captain: false,
    x: 15, y: 72,
  },
  {
    name: "Roy Keane",
    team: "Man United",
    nationality: "Ireland",
    position: "CDM",
    jerseyNumber: 16,
    age: 32,
    rating: 99,
    image: "/players/roy_keane.jpg",
    captain: false,
    x: 50, y: 55,
  },
  {
    name: "Ricardo Kaká",
    team: "AC Milan",
    nationality: "Brazil",
    position: "CAM",
    jerseyNumber: 22,
    age: 25,
    rating: 99,
    image: "/players/kaka.jpg",
    captain: false,
    x: 75, y: 48,
  },
  {
    name: "Mesut Özil",
    team: "Arsenal",
    nationality: "Germany",
    position: "CAM",
    jerseyNumber: 10,
    age: 27,
    rating: 99,
    image: "/players/ozil.webp",
    captain: false,
    x: 25, y: 48,
  },
  {
    name: "Cristiano Ronaldo",
    team: "Man United",
    nationality: "Portugal",
    position: "RW",
    jerseyNumber: 7,
    age: 23,
    rating: 99,
    image: "/players/cr7.jpg",
    captain: false,
    x: 80, y: 22,
  },
  {
    name: "Lionel Messi",
    team: "Barcelona",
    nationality: "Argentina",
    position: "LW",
    jerseyNumber: 10,
    age: 24,
    rating: 99,
    image: "/players/messi.jpg",
    captain: false,
    x: 20, y: 22,
  },
  {
    name: "Dimitar Berbatov",
    team: "Man United",
    nationality: "Bulgaria",
    position: "ST",
    jerseyNumber: 9,
    age: 29,
    rating: 99,
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Dimitar_Berbatov_2012.jpg/640px-Dimitar_Berbatov_2012.jpg",
    captain: false,
    x: 50, y: 14,
  },
];

export default players;
